name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: ${{ matrix.arch }}

    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -A ${{ matrix.arch=='x64' && 'x64' || 'Win32' }}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release

    - name: Package
      run: |
        mkdir publish
        cp build/Release/*.exe publish/ || true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ShakeToFindCursor-${{ matrix.arch }}
        path: publish/*

  release:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ShakeToFindCursor-x64/*
          ShakeToFindCursor-x86/*
        draft: false
        prerelease: false